// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_get_the_hang_of_it = "CgkIrdDX2dEZEAIQBQ"; // <GPGSID>
        public const string achievement_youre_a_smart_one = "CgkIrdDX2dEZEAIQBg"; // <GPGSID>
        public const string achievement_final_act__outcome = "CgkIrdDX2dEZEAIQBA"; // <GPGSID>
        public const string achievement_its_showtime = "CgkIrdDX2dEZEAIQAA"; // <GPGSID>
        public const string achievement_second_act__plot_point = "CgkIrdDX2dEZEAIQAw"; // <GPGSID>
        public const string achievement_star_psycho = "CgkIrdDX2dEZEAIQBw"; // <GPGSID>
        public const string achievement_catppetite = "CgkIrdDX2dEZEAIQCA"; // <GPGSID>
        public const string achievement_first_act__exposition = "CgkIrdDX2dEZEAIQAg"; // <GPGSID>

}

